### ISSUE TITLE
Oculus store games support/ideas for how to make them work?

### ISSUE THREAD

**Issue by catgirlcataclysm** [BnuuySolutions/OculusAmeliorated#2] opened 2024-03-10 16:06 UTC
I've recently been playing through Lone Echo 2, and I absolutely love it. I was wondering if with something like this, there would be a way to run games like it, that are exclusive to the Oculus store on linux? I understand that the point of the project is to remove the dependency on the store app, I'm just wondering if there's possibly a way to run those exclusives at all. (maybe revive + this driver somehow?)

**Comment by BoofOof32** [comment] 2024-04-09 11:33
You have _no_ idea how refreshing it is to see that I'm not alone on this sentiment.

years ago I wanted to see if I could get Lone Echo running on Linux as well. I saw an [issue thread on Revive's github](https://github.com/LibreVR/Revive/issues/1571) regarding Linux support that was dead for years, and I commented hoping to get the conversation rolling. Thankfully I did, and it even caught the attention of a few people smarter than me on it, and [someone manged to get a patch merged into wine](https://github.com/LibreVR/Revive/issues/1571#issuecomment-1468988764).

Right now, you can install Revive in a Proton prefix, and it even appears in SteamVR's dashboard, but I don't know whether it can run any Rift games yet nowadays

**Comment by catgirlcataclysm** [comment] 2024-04-09 11:56
interesting, I'll have to try it

**Comment by BoofOof32** [comment] 2024-04-10 01:15
Decided to dust off ALVR and poke around with VR on Linux. I got around to following this [comment that was intended for Condor 2](https://github.com/LibreVR/Revive/issues/1571#issuecomment-1793756901). I applied this to Lone Echo, switching the DLLs with their 64-bit counterparts. 
The good news is it no longer fails to initialize the OVR Runtime

The bad news is that it fails the entitlement check 
![image](https://github.com/BnuuySolutions/OculusAmeliorated/assets/66644514/b2b995ee-bfaf-4896-9a29-2006bdcff748)

Little annoying, but this is a step in the right direction, I'll just need to find a way to bypass the entitlement checks

**Comment by BoofOof32** [comment] 2024-04-10 22:31
So trying a handful of solutions, I can't get the game to budge whatsoever. I haven't really had any luck with any game I've tested so far. LE1 and 2 both fail entitlement no matter what you do (no, not even cracked versions work). And testing EchoVR causes it to crash on an unknown error 1/4 of the time, and failing to initialize the OVR session 3/4 of the time.

My methods could be flawed, but we are probably still missing crucial pieces of the puzzle for getting these games running. We will probably need to get the Oculus Software to actually run on Wine

**Comment by whatdahopper** [comment] 2024-12-20 22:28
Not supported, won't be supported in the future due to piracy/legal concerns.

**Closed as completed by whatdahopper** 2024-12-20 22:28 UTC
